// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnQ7hQqGi7G4mDaLzpoUdt2qt7Bgg0Y8I',
    appId: '1:92834692727:web:afd83dc04e1bb470a1d072',
    messagingSenderId: '92834692727',
    projectId: 'digital-khata-original-4494',
    authDomain: 'digital-khata-original-4494.firebaseapp.com',
    storageBucket: 'digital-khata-original-4494.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhJAvcMGUOhGfwVKVbzBN1DQKTfJcDDA',
    appId: '1:92834692727:android:2fa251a4eb93207fa1d072',
    messagingSenderId: '92834692727',
    projectId: 'digital-khata-original-4494',
    storageBucket: 'digital-khata-original-4494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNiKVvA5C0_nr7yuhSopfrJz-hwVerdc',
    appId: '1:92834692727:ios:4b18bdfa697a1d0aa1d072',
    messagingSenderId: '92834692727',
    projectId: 'digital-khata-original-4494',
    storageBucket: 'digital-khata-original-4494.appspot.com',
    iosBundleId: 'com.vardan.dkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvNiKVvA5C0_nr7yuhSopfrJz-hwVerdc',
    appId: '1:92834692727:ios:4b18bdfa697a1d0aa1d072',
    messagingSenderId: '92834692727',
    projectId: 'digital-khata-original-4494',
    storageBucket: 'digital-khata-original-4494.appspot.com',
    iosBundleId: 'com.vardan.dkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnQ7hQqGi7G4mDaLzpoUdt2qt7Bgg0Y8I',
    appId: '1:92834692727:web:9ef4ea450b87b551a1d072',
    messagingSenderId: '92834692727',
    projectId: 'digital-khata-original-4494',
    authDomain: 'digital-khata-original-4494.firebaseapp.com',
    storageBucket: 'digital-khata-original-4494.appspot.com',
  );
}
